services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf_chat_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    restart: unless-stopped
